;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
gl=git log --oneline --all --graph --decorate  $*
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls
history=cat "%CMDER_ROOT%\config\.history"
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"
redisLocalClient=call "%CMDER_ROOT%\plugin\script\Redis\redis_LocalClient.bat"
redisStart=call "%CMDER_ROOT%\plugin\script\Redis\startRedisService.bat"
redisStop=call "%CMDER_ROOT%\plugin\script\Redis\stopRedisService.bat"
ethInitMain=call "%CMDER_ROOT%\plugin\script\Eth\ethinit.bat" mainNode
ethInitNode=call "%CMDER_ROOT%\plugin\script\Eth\ethinit.bat" $1
ethDelNode=call "%CMDER_ROOT%\plugin\script\Eth\ethdel.bat" $1
ethStart=call "%CMDER_ROOT%\plugin\script\Eth\ethstart.bat" $1 $2 $3 $4 $5
ethDelHash=call "%CMDER_ROOT%\plugin\script\Eth\ethdelhash.bat"
ethState=call "%CMDER_ROOT%\plugin\script\Eth\ethstate.bat"
ethNet=call "%CMDER_ROOT%\plugin\script\Eth\ethnet.bat" $1
icxx=call "%CMDER_ROOT%\plugin\script\Xmake\C++Init.bat" $1
cdxx=call "%CMDER_ROOT%\plugin\script\common\cdWork.bat"
mxx=mvn clean package -U -DskipTests
gp=xmake project -k vs2017 -m "debug,release" -a "x86,x64" 
